apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: mazumo-apps
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./apps/mazumo
  prune: true
  sourceRef:
    kind: GitRepository
    name: mazumo-apps
  targetNamespace: default
