apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: nginx
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./app
  prune: true
  sourceRef:
    kind: GitRepository
    name: nginx
  targetNamespace: default
